if(EXISTS "/home/zpl/workspace/MiniOB-0xA/src/unitest/mem_pool_test[1]_tests.cmake")
  include("/home/zpl/workspace/MiniOB-0xA/src/unitest/mem_pool_test[1]_tests.cmake")
else()
  add_test(mem_pool_test_NOT_BUILT mem_pool_test_NOT_BUILT)
endif()
