if(EXISTS "/home/zpl/workspace/MiniOB-0xA/src/unitest/persist_test[1]_tests.cmake")
  include("/home/zpl/workspace/MiniOB-0xA/src/unitest/persist_test[1]_tests.cmake")
else()
  add_test(persist_test_NOT_BUILT persist_test_NOT_BUILT)
endif()
