if(EXISTS "/home/zpl/workspace/MiniOB-0xA/src/unitest/pidfile_test[1]_tests.cmake")
  include("/home/zpl/workspace/MiniOB-0xA/src/unitest/pidfile_test[1]_tests.cmake")
else()
  add_test(pidfile_test_NOT_BUILT pidfile_test_NOT_BUILT)
endif()
