if(EXISTS "/home/zpl/workspace/MiniOB-0xA/src/unitest/rc_test[1]_tests.cmake")
  include("/home/zpl/workspace/MiniOB-0xA/src/unitest/rc_test[1]_tests.cmake")
else()
  add_test(rc_test_NOT_BUILT rc_test_NOT_BUILT)
endif()
